# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.cache/wt [current_project]
set_property parent.project_path /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_ip /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.srcs/sources_1/ip/BRAM18x1k/BRAM18x1k.xci
set_property is_locked true [get_files /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.srcs/sources_1/ip/BRAM18x1k/BRAM18x1k.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top BRAM18x1k -part xc7z020clg484-1 -mode out_of_context
rename_ref -prefix_all BRAM18x1k_
write_checkpoint -noxdef BRAM18x1k.dcp
catch { report_utilization -file BRAM18x1k_utilization_synth.rpt -pb BRAM18x1k_utilization_synth.pb }
if { [catch {
  file copy -force /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.runs/BRAM18x1k_synth_1/BRAM18x1k.dcp /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.srcs/sources_1/ip/BRAM18x1k/BRAM18x1k.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.srcs/sources_1/ip/BRAM18x1k/BRAM18x1k_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.srcs/sources_1/ip/BRAM18x1k/BRAM18x1k_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.srcs/sources_1/ip/BRAM18x1k/BRAM18x1k_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.srcs/sources_1/ip/BRAM18x1k/BRAM18x1k_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
