# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.cache/wt [current_project]
set_property parent.project_path /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files -quiet /home/tsotne/git/ETSE_GDSP/src/ip/vivado/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files /home/tsotne/git/ETSE_GDSP/src/ip/vivado/blk_mem_gen_0/blk_mem_gen_0.dcp]
add_files -quiet /home/tsotne/git/ETSE_GDSP/src/ip/vivado/xbip_dsp48_macro_0/xbip_dsp48_macro_0.dcp
set_property used_in_implementation false [get_files /home/tsotne/git/ETSE_GDSP/src/ip/vivado/xbip_dsp48_macro_0/xbip_dsp48_macro_0.dcp]
read_vhdl -library xil_defaultlib {
  /home/tsotne/git/ETSE_GDSP/src/lib/txt_util.vhd
  /home/tsotne/git/ETSE_GDSP/src/ip/vivado/blk_mem_gen_0/sim/blk_mem_gen_0.vhd
  /home/tsotne/git/ETSE_GDSP/src/lib/MATRIX_MUL_IP_CORE_LIBRARY_Syn.vhd
  /home/tsotne/git/ETSE_GDSP/src/hdl/BRAM_WRAPPER_V2.vhd
  /home/tsotne/git/ETSE_GDSP/src/hdl/CONTROL_UNIT_S_INT.vhd
  /home/tsotne/git/ETSE_GDSP/src/hdl/MATRIX_MUL_IP_CORE_S_INT.vhd
}
synth_design -top MATRIX_MUL_IP_CORE_S_INT -part xc7z020clg484-1
write_checkpoint -noxdef MATRIX_MUL_IP_CORE_S_INT.dcp
catch { report_utilization -file MATRIX_MUL_IP_CORE_S_INT_utilization_synth.rpt -pb MATRIX_MUL_IP_CORE_S_INT_utilization_synth.pb }
