# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.srcs/sources_1/ip/DSP_INPUT_C/DSP_INPUT_C.xci
# IP: The module: 'DSP_INPUT_C' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.srcs/sources_1/ip/DSP_INPUT_C/DSP_INPUT_C_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP_INPUT_C'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.srcs/sources_1/ip/DSP_INPUT_C/DSP_INPUT_C.xci
# IP: The module: 'DSP_INPUT_C' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tsotne/git/ETSE_GDSP/project/vivado/s_int/s_int.srcs/sources_1/ip/DSP_INPUT_C/DSP_INPUT_C_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP_INPUT_C'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
